### ISSUE TITLE
Prepare Outline for Week 10: Introduction to Concurrency, Threads, and Thread API

### ISSUE THREAD

**Issue by entelecheia** [chu-aie/os-2024#156]
## Description:

As part of the Operating Systems 2024 course, we need to prepare an outline for the tenth week of the course. The main topics to be covered in this week are:

1. Introduction to Concurrency

   - Definition and importance of concurrency in operating systems
   - Benefits and challenges of concurrent programming
   - Examples of concurrent systems

2. Concurrency and Threads

   - Concept of threads and their relation to processes
   - Advantages of using threads over processes
   - Multithreading and its role in achieving concurrency
   - Thread states and lifecycle

3. Thread API
   - Overview of the thread API in popular programming languages (e.g., C, Java, Python)
   - Creating and managing threads
   - Thread synchronization primitives (e.g., locks, semaphores, condition variables)
   - Thread communication and data sharing

## Tasks:

- [ ] Research and gather relevant materials on concurrency, threads, and thread API
- [ ] Create a detailed outline for each subtopic
- [ ] Prepare code examples demonstrating the usage of threads and thread synchronization primitives
- [ ] Include diagrams or illustrations to visualize thread states and interactions
- [ ] Provide references to additional resources for further reading
- [ ] Review and refine the outline based on feedback from the course instructor and teaching assistants
